name: "GitHub App Check Trigger"
description: "Trigger a check run in your custom GitHub App"
author: "Autonoma"

inputs:
  repository:
    description: "Repository name (owner/repo)"
    default: ${{ github.repository }}
  sha:
    description: "Commit SHA to create the check for"
    default: ${{ github.sha }}
  event-type:
    description: "Type of event (push, pull_request, etc.)"
    default: ${{ github.event_name }}
  pr-number:
    description: "Pull request number (if applicable)"
    default: ${{ github.event.pull_request.number || '' }}
  branch:
    description: "Branch name (without refs/heads/)"
    default: ${{ github.ref_name }}
  test-id:
    description: "The id of the test to run"
    default: "App Validation"

outputs:
  status:
    description: "Status of the API call (success/failure)"
    value: ${{ steps.create-check.outputs.status }}
  message:
    description: "Response message from the API"
    value: ${{ steps.create-check.outputs.message }}

runs:
  using: "composite"
  steps:
    - name: Notify Service
      id: notify-service
      shell: bash
      run: |
        echo "Notifying service about ${{ inputs.event-type }} event on ${{ inputs.repository }}"
        
        # Create GitHub token header for your service to use
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Token: ${{ github.token }}" \
          -d '{
            "repository": "${{ inputs.repository }}",
            "sha": "${{ inputs.sha }}",
            "event_type": "${{ inputs.event-type }}",
            "pr_number": "${{ inputs.pr-number }}",
            "branch": "${{ inputs.branch }}",
            "test_id": "${{ inputs.test-id}}"
          }' \
          "${{ inputs.service-url }}")
        
        # Set output based on HTTP status code
        if [ $? -eq 0 ]; then
          echo "Service notified successfully"
          echo "status=success" >> $GITHUB_OUTPUT
          echo "message=Service notified successfully" >> $GITHUB_OUTPUT
        else
          echo "Failed to notify service"
          echo "status=failure" >> $GITHUB_OUTPUT
          echo "message=Failed to notify service" >> $GITHUB_OUTPUT
        fi
